//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khlebnyy_magazin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket_Produck
    {
        public int id_session { get; set; }
        public int id_produkta { get; set; }
        public int kol { get; set; }
        public bool PayStarys { get; set; }
    
        public virtual produkt produkt { get; set; }
        public virtual session session { get; set; }
    }
}
