//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khlebnyy_magazin.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class khlebnyy_magazinEntities : DbContext
    {
        public khlebnyy_magazinEntities()
            : base("name=khlebnyy_magazinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket_Produck> Basket_Produck { get; set; }
        public virtual DbSet<kategorii_towar> kategorii_towar { get; set; }
        public virtual DbSet<produkt> produkts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
