//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khlebnyy_magazin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produkt()
        {
            this.Basket_Produck = new HashSet<Basket_Produck>();
        }
    
        public int id_produkta { get; set; }
        public string nazvaniye { get; set; }
        public Nullable<int> tsena { get; set; }
        public Nullable<int> id_kategori { get; set; }
        public string opisanie { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket_Produck> Basket_Produck { get; set; }
        public virtual kategorii_towar kategorii_towar { get; set; }
    }
}
